import type { DataProfileResponse } from '../types/analysis';

interface AIInsightsProps {
  data: DataProfileResponse;
}

export default function AIInsights({ data }: AIInsightsProps) {
  return (
    <div className="w-full max-w-6xl mx-auto space-y-6">
      {/* AI Insights Card */}
      <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg shadow-md p-6 border border-purple-200">
        <div className="flex items-start gap-3 mb-4">
          {/* AI Icon */}
          <div className="flex-shrink-0">
            <div className="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center">
              <svg
                className="w-6 h-6 text-white"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                />
              </svg>
            </div>
          </div>

          <div className="flex-1">
            <h3 className="text-lg font-semibold text-gray-800 mb-1">
              🤖 AI-Powered Analysis
            </h3>
            <p className="text-sm text-gray-600">
              Generated by Claude Sonnet 4.5
            </p>
          </div>
        </div>

        <div className="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
          <p className="text-gray-700 leading-relaxed whitespace-pre-line">
            {data.ai_insights}
          </p>
        </div>
      </div>

      {/* Recommendations Card */}
      {data.recommendations && data.recommendations.length > 0 && (
        <div className="bg-white rounded-lg shadow-md border border-gray-200 overflow-hidden">
          <div className="px-6 py-4 bg-gradient-to-r from-yellow-50 to-orange-50 border-b border-orange-200">
            <div className="flex items-center gap-2">
              <svg
                className="w-5 h-5 text-orange-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              <h3 className="text-lg font-semibold text-gray-800">
                Recommendations
              </h3>
            </div>
          </div>

          <div className="p-6">
            <ul className="space-y-3">
              {data.recommendations.map((recommendation, index) => (
                <li key={index} className="flex items-start gap-3 group">
                  <div className="flex-shrink-0 mt-1">
                    <div className="w-6 h-6 rounded-full bg-orange-100 flex items-center justify-center group-hover:bg-orange-200 transition-colors">
                      <span className="text-xs font-bold text-orange-600">
                        {index + 1}
                      </span>
                    </div>
                  </div>
                  <p className="text-gray-700 flex-1 leading-relaxed">
                    {recommendation}
                  </p>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}
